routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\SubscriptionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');

Route::get('/help', fn() => view('blogs.help'))->name('help');

Route::get('/dashboard', fn() => view('dashboard'))
        ->middleware(['auth'])
        ->name('dashboard');

Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show');
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag');


require __DIR__.'/auth.php';

//Application routes
//NOTE: have used raw url instead of categories.destroy

Route::middleware(['auth'])->group(function() {

    Route::delete('categories/{category}/trash', [CategoriesController::class, 'trash'])->name('categories.trash');
    Route::get('categories/trashed', [CategoriesController::class, 'trashed'])->name('categories.trashed');
    Route::put('categories/{category}/restore', [CategoriesController::class, 'restore'])->name('categories.restore');
    Route::resource('categories', CategoriesController::class);

    Route::delete('tags/{tag}/trash/', [TagsController::class, 'trash'])->name('tags.trash');
    Route::get('tags/trashed', [TagsController::class, 'trashed'])->name('tags.trashed');
    Route::put('tags/{tag}/restore', [TagsController::class, 'restore'])->name('tags.restore');
    Route::resource('tags', TagsController::class);

    Route::delete('posts/{post}/trash', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('post.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');

    Route::get('posts/drafts/', [PostsController::class, 'draft'])->name('posts.drafts');
    Route::put('posts/{post}/publish', [PostsController::class, 'publish'])->name('posts.publish');
    Route::get('posts/{post}/preview', [PostsController::class, 'preview'])->name('posts.preview');

    Route::resource('posts', PostsController::class);


    //Subscription routes
    Route::get('subscriptions/add', [SubscriptionsController::class, 'add'])->name('subscriptions.add');
    Route::post('subscriptions', [SubscriptionsController::class, 'store'])->name('subscriptions.store');
    Route::delete('subscriptions/{subscription}/cancel', [SubscriptionsController::class, 'cancel'])->name('subscriptions.cancel');

    //Comments routes
    Route::post('posts/{post}/comments', [CommentsController::class, 'store'])->name('posts.comments.store');
    Route::put('posts/{post}/comments/{comment}/edit', [CommentsController::class, 'update'])->name('posts.comments.update');
    Route::get('posts/{post}/comments/{comment}', [CommentsController::class, 'reply'])->name('posts.comments.reply');
    Route::post('posts/{post}/comments/{comment}/reply', [CommentsController::class, 'replyStore'])->name('posts.comments.store.reply');
});

Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::get('users/{user}/edit', [UsersController::class, 'edit'])->name('users.edit');
    Route::put('users/{user}', [UsersController::class, 'update'])->name('users.update');
    Route::delete('users/{user}', [UsersController::class, 'destroy'])->name('users.destroy');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.remove-admin');
    Route::put('posts/{post}/approve', [PostsController::class, 'approve'])->name('posts.approve');
    Route::put('posts/{post}/disapprove', [PostsController::class, 'disApprove'])->name('posts.disapprove');

    Route::get('/blogs', [PostsController::class, 'blogs'])->name('blogs.index');
    Route::get('/approved/blogs', [PostsController::class, 'approved'])->name('approved.blogs');
    Route::get('/disapproved/blogs', [PostsController::class, 'disapproved'])->name('disapproved.blogs');

    Route::get('/blogs/categories/{category}', [PostsController::class, 'showCategory'])->name('blogs.category');

    Route::get('/subscriptions', [SubscriptionsController::class, 'index'])->name('subscriptions.index');
});

Route::group([
    'prefix' => 'timepasschecking',
    'as' => 'timepasschecking.',
    'namespace' => "\App\Http\Controllers"
], function () {
    Route::get('/timepass', function () {
        return "hello timepass";
    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = ['id'];

    protected $dates = ['published_at', 'approved_at', 'disapproved_at']; //carbon

    //Accessor
    public function getImagePathAttribute()
    {
        return 'storage/'.$this->image;
    }

    /**
     * Relationship methods
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * queryscopes
    */
    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now());
    }

    public function scopeDrafted($query)
    {
        return $query->where('published_at', '>', now());
    }

    public function scopeSearch($query): Builder
    {
        $search = request('search');
        if ($search) {
            return $query->where('title', 'LIKE', "%$search%");
        }
        return $query;
    }

    public function scopeApproved($query)
    {
        return $query->where('approved_at', '!=', null);
    }

    public function scopeDisapproved($query)
    {
        return $query->where('disapproved_at', '!=', null);
    }

    /**
     * Custom methods
     */

    public function hasTag(int $tag_id)
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    public function isApproved(): bool
    {
        return isset($this->approved_at) && (!isset($this->disapproved_at));
    }

    public function isDisapproved(): bool
    {
        return isset($this->disapproved_at) && (!isset($this->approved_at));
    }

    public function isPending(): bool
    {
        return !($this->isApproved() && $this->isDisapproved());
    }

}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Posts\CreatePostRequest;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Http\Request;

class PostsController extends Controller
{

    public function __construct()
    {
        $this->middleware(['verifyCategoriesCount'])->only('create', 'store');
        $this->middleware(['verifyTagsCount'])->only('create', 'store');
        $this->middleware(['validateUser'])->only('edit', 'update', 'destroy', 'trash');
        $this->middleware(['validateUserPreview'])->only('preview');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth()->user()->isAdmin())
        {
            $posts = Post::latest('published_at')->published()->paginate(3);
        } else {

            $posts = Post::where('user_id', auth()->id())->published()->paginate(3);
        }

        return view('posts.index', compact('posts'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();

        return view('posts.create', compact(['categories', 'tags']));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $image = $request->file('image')->store('images/posts');

        $post = Post::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'content' => $request->content,
            'category_id' => $request->category_id,
            'user_id' => auth()->id(),
            'image' => $image,
            'published_at' => $request->published_at
        ]);

        $post->tags()->attach($request->tags);

        session()->flash('success', 'Post Created Successfully');

        return redirect(route('posts.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();

        return view('posts.edit', compact(['post', 'categories', 'tags']));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only('title', 'excerpt', 'content', 'published_at', 'category_id');

        if ($request->hasFile('image')) {
            $image = $request->image->store('images/posts');
            $data['image'] = $image;
            $post->deleteImage();
        }

        $post->update($data);

        $post->tags()->sync($request->tags);

        session()->flash('success', 'Post update successfully');

        return redirect(route('posts.index'));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->deleteImage();
        $post->forceDelete();
        session()->flash('success', 'Post deleted successfully');
        return redirect(route('posts.index'));
    }

    public function trashed()
    {
        $trashed = Post::onlyTrashed()->paginate(10);
        return view('posts.trashed', ['posts' => $trashed]);
    }

    public function trash(Post $post)
    {
        $post->delete();
        session()->flash('success', 'Post Trashed');
        return redirect(route('posts.index'));
    }

    public function restore($id)
    {
        $trashedPost = Post::onlyTrashed()->findOrFail($id);
        $trashedPost->restore();
        session()->flash('success', 'Post restored successfully');
        return redirect(route('posts.index'));
    }

    public function draft()
    {
        $posts = Post::latest('published_at')->drafted()->paginate(3);

        return view('posts.draft', compact('posts'));
    }

    public function publish(int $postId)
    {
        $post = Post::findOrFail($postId);
        $post->update(['published_at' => now()]);
        session()->flash('success', $post->name . " published successfully");
        return redirect(route('posts.index'));

    }

    public function approve(Post $post)
    {
       // dd($post->author->name);
        $data = [
            'approved_at' => now(),
            'approver_id' => auth()->id(),
            'disapproved_at' => null,
            'disapprover_id' => null
        ];

        $post->update($data);

       session()->flash('success', $post->author->name . " posts approved successfully");
       return redirect(route('posts.index'));
    }

    public function disApprove(Request $request, Post $post)
    {

        $data = [
            'disapprover_id' => auth()->id(),
            'disapproved_at' => now(),
            'disapproved_status' => $request->message,
            'approved_at' => null,
            'approver_id' => null
        ];

        $post->update($data);

        session()->flash('success', $post->author->name . " posts disapproved successfully");
        return redirect(route('posts.index'));
    }

    public function preview(Post $post)
    {
        $tags = Tag::all();
        $categories = Category::all();

        return view('blogs.post', compact(['post', 'tags', 'categories']));
    }

    public function blogs()
    {
        $categories = Category::all();
        $blogs = Post::latest('published_at')->published()->paginate(3);
        return view('Blog.blog', ['posts' => $blogs, 'categories' => $categories]);
    }

    public function approved()
    {
        $categories = Category::all();
        $approvedPosts = Post::approved()->paginate(3);
        return view('Blog.approved', ['posts' => $approvedPosts, 'categories' => $categories]);
    }

    public function disapproved()
    {
        $categories = Category::all();
        $disapprovedPosts = Post::disapproved()->paginate(3);
        return view('Blog.disapproved', ['posts' => $disapprovedPosts, 'categories' => $categories]);
    }

    public function showCategory(int $categoryId)
    {
        $categories = Category::all();
        $singleCategory = Category::findOrFail($categoryId);
        //dd($category->name);
        return view('Blog.show', compact('singleCategory', 'categories'));
    }

}

resources/views/posts/create.blade.php
@extends('layouts.admin-panel.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css">


@endsection
@section('content')
<div class="card">
    <div class="card-header"><h2>Add New Post</h2></div>
    <div class="card-body">
        <form action="{{ route('posts.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
              <label for="title">Title</label>
              <input type="text"
                    class="form-control @error('title') is-invalid @enderror"
                    id="title"
                    value="{{ old('title') }}"
                    placeholder="Enter Post Title"
                    name = "title">
                @error('title')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="excerpt">Excerpt</label>
                <input type="text"
                      class="form-control @error('excerpt') is-invalid @enderror"
                      id="excerpt"
                      value="{{ old('excerpt') }}"
                      placeholder="Enter Post Excerpt"
                      name = "excerpt">
                  @error('excerpt')
                      <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                  @enderror
            </div>


            <div class="form-group">
              <label for="content">Content</label>
                <input type="hidden" id="content" name="content" value="{{ old('content') }}">
                <trix-editor input="content"></trix-editor>
                @error('content')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="category">Category</label>
                <select name="category_id" id="category_id" class="form-control select2">
                    <option></option>
                    @foreach ($categories as $category)
                        @if($category->id == old('category_id'))
                            <option value="{{ $category_id }}" selected>
                            {{ $category->name }}</option>
                        @else
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endif
                    @endforeach
                </select>
                @error('category_id')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="tags">Tags</label>
                <select name="tags[]" id="tags" class="form-control select2" multiple>
                    <option></option>
                    @foreach ($tags as $tag)
                        <option value="{{ $tag->id }}"
                        {{ (old('tags') && (in_array($tag->id, old('tags'))) ? 'selected' : '') }}>{{ $tag->name }}</option>
                    @endforeach
                </select>
                @error('tags')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="published_at">Published At</label>
                <input type="text"
                      class="form-control"
                      id="published_at"
                      value="{{ old('published_at') }}"
                      name = "published_at">
            </div>

            <div class="form-group">
                <label for="image">Image</label>
                <input type="file"
                      class="form-control @error('image') is-invalid @enderror"
                      id="image"
                      name = "image">
                  @error('image')
                      <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                  @enderror
            </div>
            <button type="submit" class="btn btn-outline-sucess">Submit</button>
        </form>
    </div>
</div>
@endsection


@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>

<script>
    $('.select2').select2({
        placeholder: 'Select an option',
        allowClear: true,
    });

    flatpickr("#published_at", {
        enableTime: true,
        dateFormat: "Y-m-d H:i",
        minDate: new Date(),
    });

</script>
@endsection

resources/views/posts/draft.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href=" {{ route('posts.create') }}" class="btn btn-outline-primary">Add Post</a>
</div>
    <div class="card">
        <div class="card-header"><h2>Posts</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset($post->image_path) }}" alt="" width="120"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>{{ $post->category->name}}</td>
                            <td>
                                <a href=" {{route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">
                                    Edit
                                </a>
                                <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $post->id }})" data-toggle="modal" data-target="#deleteModal">
                                    Delete
                                </button>
                                <form action="{{ route('posts.publish', $post->id) }}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-sm btn-success">Publish</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="" method="POST" id="deletePostForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    Are u sure, you want to delete this post?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-danger" >Delete Post</button>
                </div>
            </form>
          </div>
        </div>
    </div>

    <div class="mt-5">
        {{ $posts->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

@section('page-level-scripts')
    <script>
        //alert('hello');
        function displayModal(postId) {
            var url = "/posts/trash/" + postId;
            $("#deletePostForm").attr('action', url);
        }
    </script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.admin-panel.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css">


@endsection
@section('content')
<div class="card">
    <div class="card-header"><h2>Edit Post</h2></div>
    <div class="card-body">
        <form action="{{ route('posts.update', $post->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
              <label for="title">Title</label>
              <input type="text"
                    class="form-control @error('title') is-invalid @enderror"
                    id="title"
                    value="{{ old('title', $post->title) }}"
                    placeholder="Enter Post Title"
                    name = "title">
                @error('title')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="excerpt">Excerpt</label>
                <input type="text"
                      class="form-control @error('excerpt') is-invalid @enderror"
                      id="excerpt"
                      value="{{ old('excerpt', $post->excerpt) }}"
                      placeholder="Enter Post Excerpt"
                      name = "excerpt">
                  @error('excerpt')
                      <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                  @enderror
            </div>


            <div class="form-group">
              <label for="content">Content</label>
                <input type="hidden" id="content" name="content" value="{{ old('content', $post->content) }}">
                <trix-editor input="content"></trix-editor>
                @error('content')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="category">Category</label>
                <select name="category_id" id="category_id" class="form-control select2">
                    <option></option>
                    @foreach ($categories as $category)
                        @if($category->id == old('category_id', $post->category_id))
                            <option value="{{ $category->id }}" selected>
                            {{ $category->name }}</option>
                        @else
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endif
                    @endforeach
                </select>
                @error('category_id')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="tags">Tags</label>
                <select name="tags[]" id="tags" class="form-control select2" multiple>
                    <option></option>
                    @foreach ($tags as $tag)
                        @if((old('tags') && (in_array($tag->id, old('tags'))) || $post->hasTag($tag->id)))
                            <option value="{{ $tag->id }}" selected> {{ $tag->name }}</option>
                        @else
                        <option value="{{ $tag->id }}"> {{ $tag->name }}</option>
                        @endif
                    @endforeach
                </select>
                @error('tags')
                    <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="published_at">Published At</label>
                <input type="text"
                      class="form-control"
                      id="published_at"
                      value="{{ old('published_at', $post->published_at) }}"
                      name = "published_at">
            </div>

            <div class="form-group">
                <label for="image">Image</label>
                <input type="file"
                      class="form-control @error('image') is-invalid @enderror"
                      id="image"
                      name = "image">
                  @error('image')
                      <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                  @enderror
            </div>
            <button type="submit" class="btn btn-outline-warning">Submit</button>
        </form>
    </div>
</div>
@endsection


@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>

<script>
    $('.select2').select2({
        placeholder: 'Select an option',
        allowClear: true,
    });

    flatpickr("#published_at", {
        enableTime: true,
        dateFormat: "Y-m-d H:i",
        minDate: new Date(),
    });

</script>
@endsection