routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\SubscriptionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');

Route::get('/help', fn() => view('blogs.help'))->name('help');

Route::get('/dashboard', fn() => view('dashboard'))
        ->middleware(['auth'])
        ->name('dashboard');

Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show');
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag');


require __DIR__.'/auth.php';

//Application routes
//NOTE: have used raw url instead of categories.destroy

Route::middleware(['auth'])->group(function() {

    Route::delete('categories/{category}/trash', [CategoriesController::class, 'trash'])->name('categories.trash');
    Route::get('categories/trashed', [CategoriesController::class, 'trashed'])->name('categories.trashed');
    Route::put('categories/{category}/restore', [CategoriesController::class, 'restore'])->name('categories.restore');
    Route::resource('categories', CategoriesController::class);

    Route::delete('tags/{tag}/trash/', [TagsController::class, 'trash'])->name('tags.trash');
    Route::get('tags/trashed', [TagsController::class, 'trashed'])->name('tags.trashed');
    Route::put('tags/{tag}/restore', [TagsController::class, 'restore'])->name('tags.restore');
    Route::resource('tags', TagsController::class);

    Route::delete('posts/{post}/trash', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('post.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');

    Route::get('posts/drafts/', [PostsController::class, 'draft'])->name('posts.drafts');
    Route::put('posts/{post}/publish', [PostsController::class, 'publish'])->name('posts.publish');
    Route::get('posts/{post}/preview', [PostsController::class, 'preview'])->name('posts.preview');

    Route::resource('posts', PostsController::class);


    //Subscription routes
    Route::get('subscriptions/add', [SubscriptionsController::class, 'add'])->name('subscriptions.add');
    Route::post('subscriptions', [SubscriptionsController::class, 'store'])->name('subscriptions.store');
    Route::delete('subscriptions/{subscription}/cancel', [SubscriptionsController::class, 'cancel'])->name('subscriptions.cancel');

    //Comments routes
    Route::post('posts/{post}/comments', [CommentsController::class, 'store'])->name('posts.comments.store');
    Route::put('posts/{post}/comments/{comment}/edit', [CommentsController::class, 'update'])->name('posts.comments.update');
    Route::get('posts/{post}/comments/{comment}', [CommentsController::class, 'reply'])->name('posts.comments.reply');
    Route::post('posts/{post}/comments/{comment}/reply', [CommentsController::class, 'replyStore'])->name('posts.comments.store.reply');
});

Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::get('users/{user}/edit', [UsersController::class, 'edit'])->name('users.edit');
    Route::put('users/{user}', [UsersController::class, 'update'])->name('users.update');
    Route::delete('users/{user}', [UsersController::class, 'destroy'])->name('users.destroy');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.remove-admin');
    Route::put('posts/{post}/approve', [PostsController::class, 'approve'])->name('posts.approve');
    Route::put('posts/{post}/disapprove', [PostsController::class, 'disApprove'])->name('posts.disapprove');

    Route::get('/blogs', [PostsController::class, 'blogs'])->name('blogs.index');
    Route::get('/approved/blogs', [PostsController::class, 'approved'])->name('approved.blogs');
    Route::get('/disapproved/blogs', [PostsController::class, 'disapproved'])->name('disapproved.blogs');

    Route::get('/blogs/categories/{category}', [PostsController::class, 'showCategory'])->name('blogs.category');

    Route::get('/subscriptions', [SubscriptionsController::class, 'index'])->name('subscriptions.index');
});

Route::group([
    'prefix' => 'timepasschecking',
    'as' => 'timepasschecking.',
    'namespace' => "\App\Http\Controllers"
], function () {
    Route::get('/timepass', function () {
        return "hello timepass";
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function __construct()
    {
        $this->middleware(['admin'])->only('edit', 'update', 'trash', 'destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(10);
        //compact: as in view it is used to take array for var/object which is returned by DB and
        //passed as value to key categories which is obj/var in view, so to avoid of key => value in
        //array, we use compact() which takes var name and directly do key => value automatically.
        return view('categories.index', compact(['categories']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        // 1. Validation is already done with the help of Form request

        // 2. store the data in db
        Category::create([
            'name' => $request->name
        ]);

        //session
        session()->flash('success', 'Category created successfully');
        //3. return to index
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category) //route-model binding
    {
        return view('categories.edit', compact(['category']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->name = $request->name;
        //$category->update(['name' => '$request->name']);
        $category->save();

        //session
        session()->flash('success', 'Category Updated Successfully');

        //redirect
        return redirect(route('categories.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $categoryId)
    {
        $category = Category::onlyTrashed()->findOrFail($categoryId);

        if ($category->posts()->count() > 0) {
            session()->flash('error', 'This category cannot be deleted as it is associated with some post');
            return redirect(route('categories.index'));
        }
        $category->forceDelete();
        session()->flash('success', $category->name . ' category deleted successfully');
        return redirect(route('categories.index'));
    }

    public function trashed()
    {
        $categories = Category::onlyTrashed()->paginate(10);
        return view('categories.trashed', compact(['categories']));
    }

    public function trash(Category $category)
    {
        $category->delete();
        session()->flash('success', $category->name . ' trashed successfully');
        return redirect(route('categories.index'));
    }

    public function restore(int $categoryId)
    {
        $category = Category::onlyTrashed()->findOrFail($categoryId);
        $category->update();
        session()->flash('success', 'Category restored successfully');
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="card">
    <div class="card-header"><h2>Add New Category</h2></div>
    <div class="card-body">
        <form action="{{ route('categories.store')}}" method="POST">
            @csrf
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text"
                    class="form-control @error('name') is-invalid @enderror"
                    id="name"
                    value="{{ old('name') }}"
                    placeholder="Enter Category Name"
                    name = "name">
                @error('name')
                <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <button type="submit" class="btn btn-outline-sucess">Submit</button>
          </form>
    </div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="card">
    <div class="card-header"><h2>Update Category</h2></div>
    <div class="card-body">
        <form action="{{ route('categories.update', $category->id)}}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text"
                    class="form-control @error('name') is-invalid @enderror"
                    id="name"
                    value="{{ old('name', $category->name) }}"
                    placeholder="Enter Category Name"
                    name = "name">
                @error('name')
                <small id="emailHelp" class="form-text text-danger"> {{ $message }}</small>
                @enderror
            </div>

            <button type="submit" class="btn btn-outline-warning">Edit</button>
          </form>
    </div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href=" {{ route('categories.create') }}" class="btn btn-outline-primary">Add Category</a>
</div>
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h2>Categories</h2></div>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->name }}</td>
                            <td>
                                <a href=" {{route('categories.edit', $category->id) }}" class="btn btn-sm btn-primary">
                                    Edit
                                </a>
                                <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $category->id }})" data-toggle="modal" data-target="#deleteModal">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="" method="POST" id="deleteCategoryForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    Are u sure, you want to delete this category?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-danger" >Delete Category</button>
                </div>
            </form>
          </div>
        </div>
    </div>

    <div class="mt-5">
        {{ $categories->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

@section('page-level-scripts')
    <script>
        //alert('hello');
        function displayModal(categoryId) {
            var url = "/categories/" + categoryId + "/trash";
            $("#deleteCategoryForm").attr('action', url);
        }
    </script>
@endsection

resources/views/categories/trashed.blade.php
@extends('layouts.admin-panel.app')

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h2>Categories</h2></div>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->name }}</td>
                            <td>
                                <form action="{{ route('categories.restore', $category->id) }}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <button class="btn btn-sm btn-warning" type="submit">Restore</button>
                                </form>
                                <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $category->id }})" data-toggle="modal" data-target="#deleteModal">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="" method="POST" id="deleteCategoryForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    Are u sure, you want to delete this category?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-danger" >Delete Category</button>
                </div>
            </form>
          </div>
        </div>
    </div>

    <div class="mt-5">
        {{ $categories->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

@section('page-level-scripts')
    <script>
        //alert('hello');
        function displayModal(categoryId) {
            var url = "/categories/" + categoryId;
            $("#deleteCategoryForm").attr('action', url);
        }
    </script>
@endsection