routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\SubscriptionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');

Route::get('/help', fn() => view('blogs.help'))->name('help');

Route::get('/dashboard', fn() => view('dashboard'))
        ->middleware(['auth'])
        ->name('dashboard');

Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show');
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag');


require __DIR__.'/auth.php';

//Application routes
//NOTE: have used raw url instead of categories.destroy

Route::middleware(['auth'])->group(function() {

    Route::delete('categories/{category}/trash', [CategoriesController::class, 'trash'])->name('categories.trash');
    Route::get('categories/trashed', [CategoriesController::class, 'trashed'])->name('categories.trashed');
    Route::put('categories/{category}/restore', [CategoriesController::class, 'restore'])->name('categories.restore');
    Route::resource('categories', CategoriesController::class);

    Route::delete('tags/{tag}/trash/', [TagsController::class, 'trash'])->name('tags.trash');
    Route::get('tags/trashed', [TagsController::class, 'trashed'])->name('tags.trashed');
    Route::put('tags/{tag}/restore', [TagsController::class, 'restore'])->name('tags.restore');
    Route::resource('tags', TagsController::class);

    Route::delete('posts/{post}/trash', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('post.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');

    Route::get('posts/drafts/', [PostsController::class, 'draft'])->name('posts.drafts');
    Route::put('posts/{post}/publish', [PostsController::class, 'publish'])->name('posts.publish');
    Route::get('posts/{post}/preview', [PostsController::class, 'preview'])->name('posts.preview');

    Route::resource('posts', PostsController::class);


    //Subscription routes
    Route::get('subscriptions/add', [SubscriptionsController::class, 'add'])->name('subscriptions.add');
    Route::post('subscriptions', [SubscriptionsController::class, 'store'])->name('subscriptions.store');
    Route::delete('subscriptions/{subscription}/cancel', [SubscriptionsController::class, 'cancel'])->name('subscriptions.cancel');

    //Comments routes
    Route::post('posts/{post}/comments', [CommentsController::class, 'store'])->name('posts.comments.store');
    Route::put('posts/{post}/comments/{comment}/edit', [CommentsController::class, 'update'])->name('posts.comments.update');
    Route::get('posts/{post}/comments/{comment}', [CommentsController::class, 'reply'])->name('posts.comments.reply');
    Route::post('posts/{post}/comments/{comment}/reply', [CommentsController::class, 'replyStore'])->name('posts.comments.store.reply');
});

Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::get('users/{user}/edit', [UsersController::class, 'edit'])->name('users.edit');
    Route::put('users/{user}', [UsersController::class, 'update'])->name('users.update');
    Route::delete('users/{user}', [UsersController::class, 'destroy'])->name('users.destroy');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.remove-admin');
    Route::put('posts/{post}/approve', [PostsController::class, 'approve'])->name('posts.approve');
    Route::put('posts/{post}/disapprove', [PostsController::class, 'disApprove'])->name('posts.disapprove');

    Route::get('/blogs', [PostsController::class, 'blogs'])->name('blogs.index');
    Route::get('/approved/blogs', [PostsController::class, 'approved'])->name('approved.blogs');
    Route::get('/disapproved/blogs', [PostsController::class, 'disapproved'])->name('disapproved.blogs');

    Route::get('/blogs/categories/{category}', [PostsController::class, 'showCategory'])->name('blogs.category');

    Route::get('/subscriptions', [SubscriptionsController::class, 'index'])->name('subscriptions.index');
});

Route::group([
    'prefix' => 'timepasschecking',
    'as' => 'timepasschecking.',
    'namespace' => "\App\Http\Controllers"
], function () {
    Route::get('/timepass', function () {
        return "hello timepass";
    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = ['id'];

    protected $dates = ['published_at', 'approved_at', 'disapproved_at']; //carbon

    //Accessor
    public function getImagePathAttribute()
    {
        return 'storage/'.$this->image;
    }

    /**
     * Relationship methods
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * queryscopes
    */
    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now());
    }

    public function scopeDrafted($query)
    {
        return $query->where('published_at', '>', now());
    }

    public function scopeSearch($query): Builder
    {
        $search = request('search');
        if ($search) {
            return $query->where('title', 'LIKE', "%$search%");
        }
        return $query;
    }

    public function scopeApproved($query)
    {
        return $query->where('approved_at', '!=', null);
    }

    public function scopeDisapproved($query)
    {
        return $query->where('disapproved_at', '!=', null);
    }

    /**
     * Custom methods
     */

    public function hasTag(int $tag_id)
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    public function isApproved(): bool
    {
        return isset($this->approved_at) && (!isset($this->disapproved_at));
    }

    public function isDisapproved(): bool
    {
        return isset($this->disapproved_at) && (!isset($this->approved_at));
    }

    public function isPending(): bool
    {
        return !($this->isApproved() && $this->isDisapproved());
    }

}

resources/views/Blog/approved.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href=" {{ route('posts.create') }}" class="btn btn-outline-primary">Add Post</a>
</div>
    {{-- dropdown --}}
    <div class="btn-group mb-2 postion-relative" style="top: -55px !important">
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Approved
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{ route('blogs.index') }}">Latest</a>
          <a class="dropdown-item" href="{{ route('disapproved.blogs') }}">Disapproved</a>
        </div>
    </div>

    <div class="btn-group postion-relative" style="top: -55px !important; left: 70px">
        <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category
        </button>
        <div class="dropdown-menu">
            @foreach ($categories as $category)
                <a class="dropdown-item" href="{{ route('blogs.category', $category->id)}}">{{ $category->name }}</a>
            @endforeach
        </div>
    </div>


    <div class="card">
        <div class="card-header"><h2>Posts</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset($post->image_path) }}" alt="" width="120"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-5">
        {{ $posts->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

resources/views/Blog/blog.blade.php
@extends('layouts.admin-panel.app')

@section('content')
    {{-- dropdown --}}
    <div class="btn-group postion-relative" style="bottom: 18px !important">
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Latest
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{ route('approved.blogs')}}">Approved</a>
          <a class="dropdown-item" href="{{ route('disapproved.blogs') }}">Disapproved</a>
        </div>
    </div>

    <div class="btn-group postion-relative" style="top: -20px !important; left: 70px">
        <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category
        </button>
        <div class="dropdown-menu">
            @foreach ($categories as $category)
                <a class="dropdown-item" href="{{ route('blogs.category', $category->id)}}">{{ $category->name }}</a>
            @endforeach
        </div>
    </div>

    <div class="card">
        <div class="card-header"><h2>Posts</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset($post->image_path) }}" alt="" width="120"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>
                                @if($post->isApproved())
                                    <div class="badge rounded-pill bg-primary">
                                        Approved
                                    </div>
                                @elseif($post->isDisapproved())
                                    <div class="badge rounded-pill bg-danger">
                                        Disapproved
                                    </div>
                                    <span class="text-danger">{{ $post->disapproved_status }}</span>
                                @elseif($post->isPending())
                                    <div class="badge rounded-pill bg-warning">
                                        Pending
                                    </div>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-5">
        {{ $posts->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

resources/views/Blog/disapproved.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href=" {{ route('posts.create') }}" class="btn btn-outline-primary">Add Post</a>
</div>
    {{-- dropdown --}}
    <div class="btn-group mb-2 postion-relative" style="top: -55px !important">
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Disapproved
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{ route('blogs.index') }}">Latest</a>
          <a class="dropdown-item" href="{{ route('approved.blogs') }}">Approved</a>
        </div>
    </div>

    <div class="btn-group postion-relative" style="top: -55px !important; left: 70px">
        <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category
        </button>
        <div class="dropdown-menu">
            @foreach ($categories as $category)
                <a class="dropdown-item" href="{{ route('blogs.category', $category->id)}}">{{ $category->name }}</a>
            @endforeach
        </div>
    </div>


    <div class="card">
        <div class="card-header"><h2>Posts</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset($post->image_path) }}" alt="" width="120"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>
                                <div class="badge rounded-pill bg-danger">
                                    Disapproved
                                </div>
                                <span>{{ $post->disapproved_status }}</span>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-5">
        {{ $posts->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

resources/views/Blog/show.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href=" {{ route('posts.create') }}" class="btn btn-outline-primary">Add Post</a>
</div>
    {{-- dropdown --}}
    <div class="btn-group postion-relative" style="top: -55px !important">
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Latest
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{ route('approved.blogs')}}">Approved</a>
          <a class="dropdown-item" href="">Disapproved</a>
        </div>
    </div>

    <div class="btn-group postion-relative" style="top: -55px !important; left: 70px">
        <button type="button" value = "" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category
        </button>
        <div class="dropdown-menu">
            @foreach ($categories as $category)
                <a class="dropdown-item" href="{{ route('blogs.category', $category->id)}}">{{ $category->name }}</a>
            @endforeach
        </div>
    </div>

    <div class="card">
        <div class="card-header"><h2>Posts</h2></div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($singleCategory->posts as $post)
                        <tr>
                            <td><img src="{{ asset($post->image_path) }}" alt="" width="120"></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    {{-- <div class="mt-5">
        {{ $singleCategory->posts->links('vendor.pagination.bootstrap-4') }}
    </div> --}}
@endsection